apiVersion: apps/v1
kind: Deployment
metadata:
  name: carshop
  labels:
    app: carshop
spec:
  replicas: 1
  template:
    metadata:
      name: carshop
      labels:
        app: carshop
    spec:
      containers:
      - name: carshop
        image: narif/carshop:1
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: carshop

---
apiVersion: v1
kind: Service
metadata:
  name: carshop
spec:
  selector:
    app: carshop
  ports:
    - port: 8080
      name: http
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: carshop
spec:
  rules:
    - host: carshop.kubernetes.local
      http:
        paths:
          - path: /
            backend:
              serviceName: carshop
              servicePort: 8080
---

